# 389. Find the Difference
# Solved
# Easy
# Topics
# premium lock icon
# Companies
# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        if len(s)==0 :
            return t
        
        s_list = sorted(list(s))
        t_list = sorted(list(t))
        for i in range (0,len(t)) :
            if(i >= len(s)):
                return t_list[-1]
            if t_list[i] != s_list[i]:
                return t_list[i]
            

"""
Approach:
- First, I checked if the length of string s is zero. If it is, I returned string t as the added letter.
- Next, I converted both strings s and t into lists of characters and sorted them in ascending order.
- I then iterated through the indices of string t. During each iteration, I compared the characters at the same index in both sorted lists.
- If the index exceeds the length of string s, it means the extra character is at the end of string t, so I returned the last character of t_list.
- If I found a mismatch between the characters at the same index in both lists, I returned the character from t_list as it is the added letter.

"""